models:
  - model: pmahdavi/Llama-3.1-8B-coding
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      weight: 1.0
merge_method: linear
dtype: bfloat16
tokenizer_source: union 