merge_method: ota

parameters:
  epsilon: 1e-16 # Default epsilon for OTA, can be tuned
  normalise: none
  power: 0.5
  precond_threshold: 1e-11  # Mask elements where precond < threshold

models:
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-math-reasoning/export/exp_avg_sq.safetensors
  - model: pmahdavi/Llama-3.1-8B-coding
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-coding/export/exp_avg_sq.safetensors
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-precise-if/export/exp_avg_sq.safetensors

dtype: bfloat16
tokenizer_source: union 