merge_method: ota

parameters:
  epsilon: 1e-24 # Default epsilon for OTA, can be tuned
  normalise: none
  power: 1.0
  fallback_to_base: false # Fallback to base model for fully masked elements

models:
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-math-reasoning/export/fisher_diag_s1024_bs128.safetensors
  - model: pmahdavi/Llama-3.1-8B-coding
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-coding/export/fisher_diag_s1024_bs128.safetensors
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-precise-if/export/fisher_diag_s1024_bs128.safetensors
  - model: pmahdavi/Llama-3.1-8B-general
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-general/export/fisher_diag_s1024_bs128.safetensors
  - model: pmahdavi/Llama-3.1-8B-knowledge-recall
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-knowledge-recall/export/fisher_diag_s1024_bs128.safetensors

dtype: bfloat16
tokenizer_source: union 