merge_method: ota
base_model: meta-llama/Meta-Llama-3.1-8B

parameters:
  epsilon: 1e-24 # Default epsilon for OTA, can be tuned
  normalise: none
  power: 0.5
  precond_threshold: 5e-20  # Mask elements where (v * (w_t - w_0)^2) < threshold
  fallback_to_base: true # Fallback to base model for fully masked elements

models:
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-math-reasoning/export/exp_avg_sq.safetensors
      rank: 16
  - model: pmahdavi/Llama-3.1-8B-coding
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-coding/export/exp_avg_sq.safetensors
      rank: 16
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      preconditioner_path: pmahdavi/Llama-3.1-8B-precise-if/export/exp_avg_sq.safetensors
      rank: 16

dtype: bfloat16
tokenizer_source: union 