merge_method: dare_ties
base_model: meta-llama/Meta-Llama-3.1-8B
parameters:
  density: 0.95 # Default density for DARE-TIES, can be tuned
  weight: 1.0    # Equal weighting for all models before DARE-TIES processing

models:
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-coding-tulu3-ebs128-lr5e6-wsdcr0p4
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-general
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-knowledge-recall
    parameters:
      weight: 1.0

dtype: bfloat16
tokenizer_source: union 