merge_method: linear

models:
  - model: pmahdavi/Llama-3.1-8B-math-reasoning
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-coding
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-precise-if
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-general
    parameters:
      weight: 1.0
  - model: pmahdavi/Llama-3.1-8B-knowledge-recall
    parameters:
      weight: 1.0

dtype: bfloat16
tokenizer_source: union 